// 地城探險（狗頭人與地下城）的 Boss 資料：血量、英雄能力與牌組（整理自 HearthPwn「All Boss Decks」）。
// 牌組用英文卡名，執行時再對照遊戲內的卡牌資料；對不到的卡會被同費用的卡取代。
import type { CardClass } from '../engine/types';

export interface DungeonBoss {
  /** Boss 英雄卡（LOOTA_BOSS_xxh） */
  hero: string;
  name: string;
  cls: Exclude<CardClass, 'NEUTRAL'>;
  /** 會出現在哪幾關，以及各關的血量 */
  levels: number[];
  hp: number[];
  /** 英雄能力：預設用 power；後半段的關卡（levelUp 以上）換成 power2 */
  power: string;
  power2?: string;
  levelUp?: number;
  /** 牌組，格式 'N x 卡名, ...' */
  deck: string;
}

export const DUNGEON_BOSSES: DungeonBoss[] = [
  // ---------------------------------------------------------------- 第 1 關
  { hero: 'LOOTA_BOSS_45h', name: '竊賊賓克', cls: 'ROGUE', levels: [1], hp: [10], power: 'LOOTA_BOSS_45p', deck: "Burgly Bully, Cutpurse, One-eyed Cheat, Undercity Huckster, Southsea Deckhand, Swashburglar, Tomb Pillager, Undercity Valiant, Burgle, Fan of Knives" },
  { hero: 'LOOTA_BOSS_18h', name: '大老鼠', cls: 'HUNTER', levels: [1], hp: [10], power: 'LOOTA_BOSS_18p', deck: "Core Rager, Pint-Sized Summoner, Young Dragonhawk, Ironbeak Owl, River Crocolisk, Starving Buzzard, Stonetusk Boar, Timber Wolf, Bestial Wrath, Explosive Shot" },
  // ---------------------------------------------------------------- 第 2、3 關
  { hero: 'LOOTA_BOSS_09h', name: '霜毛', cls: 'MAGE', levels: [2, 3], hp: [15, 20], power: 'LOOTA_BOSS_09p', deck: "2x Raid Leader, 2x River Crocolisk, 2x Sen'jin Shieldmasta, 2x Bloodfen Raptor, 2x Murloc Raider, 2x Nightblade, 2x Novice Engineer, 2x Oasis Snapjaw, 2x Ogre Magi, 2x Wolfrider, 2x Arcane Intellect, 2x Fireball, 2x Arcane Explosion, 2x Arcane Missiles, 2x Polymorph" },
  { hero: 'LOOTA_BOSS_10h', name: '教士格雷夫斯', cls: 'PRIEST', levels: [2, 3], hp: [15, 20], power: 'LOOTA_BOSS_10p', deck: "2x Faceless Manipulator, 2x Abomination, 2x Acidic Swamp Ooze, 2x Injured Blademaster, 2x Leper Gnome, 2x Acolyte of Pain, 2x Lightspawn, 2x Loot Hoarder, 2x Northshire Cleric, 2x Temple Enforcer, 2x Shadow Madness, 2x Silence, Holy Nova, 2x Power Word: Shield, Mind Control, 2x Shadow Word: Pain" },
  { hero: 'LOOTA_BOSS_35h', name: '布蘭多瑪長老', cls: 'SHAMAN', levels: [2, 3], hp: [15, 20], power: 'LOOTA_BOSS_35p', deck: "2x Boulderfist Ogre, 2x Chillwind Yeti, 2x Raid Leader, 2x Sen'jin Shieldmasta, 2x Booty Bay Bodyguard, 2x Frostwolf Grunt, 2x Frostwolf Warlord, 2x Reckless Rocketeer, 2x Stonetusk Boar, 2x Wolfrider, 2x Hex, 2x Rockbiter Weapon, 2x Windfury, 2x Ancestral Healing, 2x Frost Shock" },
  { hero: 'LOOTA_BOSS_40h', name: '賽瑞歐娜', cls: 'PRIEST', levels: [2, 3], hp: [15, 20], power: 'LOOTA_BOSS_40p', deck: "Deathwing Dragonlord, Ysera, 2x Twilight Guardian, 2x Book Wyrm, 2x Duskbreaker, 2x Twilight Drake, 2x Blackwing Corruptor, 2x Netherspite Historian, 2x Sleepy Dragon, 2x Twilight Whelp, 2x Dragonfire Potion, 2x Shadow Madness, 2x Shadow Word: Horror, 2x Flash Heal, 2x Potion of Madness, 2x Spirit Lash" },
  { hero: 'LOOTA_BOSS_12h', name: '蠟燭鬍子', cls: 'ROGUE', levels: [2, 3, 6, 7], hp: [15, 20, 50, 60], power: 'LOOTA_BOSS_12p', power2: 'LOOTA_BOSS_31p', levelUp: 6, deck: "Genzo the Shark, Sneed's Old Shredder, Xaril Poisoned Mind, 2x Piloted Sky Golem, 2x Sea Giant, 2x Wind-up Burglebot, 2x Cutpurse, 2x Dark Iron Skulker, 2x Shady Dealer, 2x Vicious Fledgling, 2x Piloted Shredder, 2x Pit Snake, 2x Ship's Cannon, 2x Stoneskin Basilisk, 2x Swashburglar, 2x Magma Rager, Vanish" },
  { hero: 'LOOTA_BOSS_11h', name: '監督者莫加克', cls: 'WARRIOR', levels: [2, 3, 6, 7], hp: [15, 20, 50, 60], power: 'LOOTA_BOSS_11p', power2: 'LOOTA_BOSS_30p', levelUp: 6, deck: "2x Armorsmith, 2x Death Revenant, 2x Devilsaur Egg, 2x Frothing Berserker, 2x Nerubian Egg, 2x Acolyte of Pain, 2x Runic Egg, 2x Unstable Ghoul, 2x Blood Warriors, 2x Brawl, 2x Sudden Genesis, 2x Battle Rage, 2x Rampage, 2x Execute, 2x Fiery War Axe" },
  { hero: 'LOOTA_BOSS_05h', name: '開路者哈姆', cls: 'WARRIOR', levels: [2, 3, 6, 7], hp: [15, 20, 50, 60], power: 'LOOTA_BOSS_05p', power2: 'LOOTA_BOSS_28p', levelUp: 6, deck: "Rotface, 2x Bomb Lobber, 4x Bomb Squad, 4x Frothing Berserker, 5x Madder Bomber, 4x Axe Flinger, 8x Mad Bomber, 2x Brawl" },
  // ---------------------------------------------------------------- 第 4、5 關
  { hero: 'LOOTA_BOSS_54h', name: '詹莉‧伊夏', cls: 'MAGE', levels: [4], hp: [40], power: 'LOOTA_BOSS_54p', deck: "Ragnaros the Firelord, 2x Arcane Giant, 2x Bittertide Hydra, 2x Clockwork Giant, 2x Fel Reaver, 2x Frost Giant, 4x Giant Sand Worm, 2x Molten Giant, 2x Mountain Giant, 2x Sea Giant, 2x Snowfury Giant, 2x Frozen Crusher, 2x Bag of Stuffing, 2x Boots of Haste" },
  { hero: 'LOOTA_BOSS_17h', name: '戰吼者金佐！', cls: 'WARRIOR', levels: [4, 5], hp: [30, 40], power: 'LOOTA_BOSS_17p', deck: "2x Blubber Baron, 2x Dirty Rat, 2x Coldlight Oracle, 2x Mind Control Tech, 2x Saboteur, 2x Cruel Taskmaster, 2x Grimestreet Smuggler, 2x Public Defender, 2x Ravaging Ghoul, 2x Refreshment Vendor, 2x Novice Engineer, 2x Brawl, 2x Bring It On!, 2x Battle Rage, 2x Shield Block" },
  { hero: 'LOOTA_BOSS_06h', name: '黑種子', cls: 'DRUID', levels: [4, 5, 6, 7], hp: [30, 40, 50, 60], power: 'LOOTA_BOSS_06p', power2: 'LOOTA_BOSS_29p', levelUp: 6, deck: "2x Rattling Rascal, 2x Ancient Watcher, 2x Bomb Squad, 2x Darnassus Aspirant, 2x Doppelgangster, Humongous Razorleaf, 2x Mire Keeper, 2x Saronite Chain Gang, 2x Bilefin Tidehunter, 2x Worgen Infiltrator, Dark Wispers, 2x Living Mana, 2x Spreading Plague, 2x Living Roots, 2x Wrath, 2x Moonfire" },
  { hero: 'LOOTA_BOSS_20h', name: '硫磺看守者', cls: 'MAGE', levels: [4], hp: [30], power: 'LOOTA_BOSS_20p', deck: "Emperor Thaurissan, 2x Emperor Cobra, 2x Shieldbearer, 2x Giant Wasp, 2x Pit Snake, 13x Stone Golem, 2x Snake Trap, 2x Venomstrike Trap, 2x Bear Trap" },
  { hero: 'LOOTA_BOSS_42h', name: '雅瑞長老', cls: 'DRUID', levels: [4, 5], hp: [30, 40], power: 'LOOTA_BOSS_42p', deck: "Kun the Forgotten King, Tyrantus, Ysera, 2x Ancient of War, 2x Greedy Sprite, 2x Druid of the Claw, 2x Ironwood Golem, 2x Branching Paths, Tree of Life, 2x Ultimate Infestation, 2x Earthen Scales, 2x Innervate, 2x Lesser Jasper Spellstone, 2x Nourish, 2x Swipe, 2x Wild Growth, 2x Wrath" },
  { hero: 'LOOTA_BOSS_46h', name: '真菌術師弗勒戈', cls: 'SHAMAN', levels: [4, 5], hp: [30, 40], power: 'LOOTA_BOSS_46p', deck: "Finja, the Flying Star, 2x Murloc Warleader, Mana Tide Totem, 2x Murloc Tidecaller, 2x Primalfin Totem, Vitality Totem, 2x Bilefin Tidehunter, 2x Flametongue Totem, 2x Kobold Hermit, 2x Murloc Tidehunter, 2x Murloc Tinyfin, 2x Totem Golem, 2x Tuskarr Totemic, 2x Primal Talismans, 2x Call in the Finishers, 2x Ice Fishing, Totemic Might" },
  { hero: 'LOOTA_BOSS_19h', name: '戈穆克', cls: 'SHAMAN', levels: [4, 5, 6, 7], hp: [30, 40, 50, 60], power: 'LOOTA_BOSS_19p', power2: 'LOOTA_BOSS_33p', levelUp: 6, deck: "2x King Mukla, Millhouse Manastorm, Troggzor the Earthinator, 2x Burgly Bully, 2x Snowfury Giant, 2x Burly Rockjaw Trogg, 2x Flamewreathed Faceless, 2x Hoarding Dragon, 2x Totem Golem, 2x Tunnel Trogg, 2x Gluttonous Trogg, 2x Lava Shock, 2x Lightning Storm, Volcano, 2x Ancestral Knowledge, 2x Crushing Hand, 2x Stormforged Axe" },
  { hero: 'LOOTA_BOSS_39h', name: '克拉克斯', cls: 'WARRIOR', levels: [4, 5], hp: [30, 40], power: 'LOOTA_BOSS_39p', deck: "Geosculptor Yip, 2x Alley Armorsmith, 2x Armorsmith, 2x Drywhisker Armorer, 3x Gemstudded Golem, 2x Crush, 2x Shield Slam, 2x Sleep with the Fishes, 2x Bash, 2x Execute, 2x Shield Block, 2x Unidentified Shield, 2x Bladed Gauntlet, 2x Fiery War Axe, 2x Arcanite Reaper" },
  { hero: 'LOOTA_BOSS_37h', name: '狂法師黎瑞絲', cls: 'MAGE', levels: [4, 5], hp: [30, 40], power: 'LOOTA_BOSS_37p', deck: "Archmage Antonidas, 4x Arcane Giant, 20x Flamewaker, 5x Arcane Intellect" },
  { hero: 'LOOTA_BOSS_51h', name: '吟遊詩人羅賽爾', cls: 'ROGUE', levels: [4, 5], hp: [30, 40], power: 'LOOTA_BOSS_51p', deck: "Barnes, 2x Elven Minstrel, 2x Knife Juggler, 2x Questing Adventurer, 2x Stampeding Kodo, 2x Annoy-o-Tron, Antique Healbot, 2x Shado-Pan Rider, 2x Swashburglar, 2x Evasion, 2x Counterfeit Coin, 2x Lesser Onyx Spellstone, 2x Thistle Tea, 2x Backstab, 2x Eviscerate, 2x Perdition's Blade" },
  { hero: 'LOOTA_BOSS_16h', name: '靈語者阿祖恩', cls: 'PRIEST', levels: [4, 5], hp: [30, 40], power: 'LOOTA_BOSS_16p', deck: "Arfus, Barnes, N'Zoth, the Corruptor, Spiritsinger Umbra, 2x Obsidian Statue, Bone Drake, 2x Crystalline Oracle, Onyx Bishop, 2x Shallow Gravedigger, 2x Shifting Shade, 2x Loot Hoarder, 2x Mistress of Mixtures, 2x Tortollan Shellraiser, Awaken the Makers, 2x Eternal Servitude, 2x Shadow Essence, Holy Nova, 2x Shadow Word: Death, 2x Shadow Word: Pain" },
  { hero: 'LOOTA_BOSS_13h', name: '小偷薩朵克', cls: 'ROGUE', levels: [4, 5], hp: [30, 40], power: 'LOOTA_BOSS_13p', deck: "2x Stonetusk Boar, 2x Stoneskin Basilisk, Patches the Pirate, 2x Gadgetzan Ferryman, 2x Southsea Deckhand, 2x Bilefin Tidehunter, 2x Fire Fly, 2x Glacial Shard, 2x Igneous Elemental, 2x Swashburglar, 2x Youthful Brewmaster, 2x Novice Engineer, The Caverns Below, 2x Preparation, Mimic Pod, 2x Backstab, 2x Shadowstep, Vanish" },
  // ---------------------------------------------------------------- 第 5～7 關
  { hero: 'LOOTA_BOSS_36h', name: '伊克利德', cls: 'DRUID', levels: [5, 6], hp: [20, 20], power: 'LOOTA_BOSS_36p', deck: "2x Bittertide Hydra, 2x Corridor Creeper, 2x Addled Grizzly, 2x Defender of Argus, 2x Savage Combatant, 2x Ticking Abomination, 2x Mukla's Champion, 2x Tentacle of N'Zoth, 2x Mark of the Wild, 2x Mark of Nature, 2x Living Roots, 2x Poison Seeds, 2x Power of the Wild, 2x Webweave, 2x Wrath" },
  { hero: 'LOOTA_BOSS_15h', name: '喬治與卡爾', cls: 'PALADIN', levels: [6], hp: [60], power: 'LOOTA_BOSS_15p', deck: "2x Aldor Peacekeeper, 2x Grimestreet Enforcer, 2x Lightfused Stegodon, 2x Warhorse Trainer, 2x Quartermaster, Blood Knight, 2x Consecration, 2x Equality, 2x Lost in the Jungle, 2x Muster for Battle, 2x Stand Against Darkness, 4x Tag Team, 2x Rallying Blade, 2x Vinecleaver, Divine Favor" },
  { hero: 'LOOTA_BOSS_21h', name: '大蟲諾吸', cls: 'WARRIOR', levels: [6], hp: [40], power: 'LOOTA_BOSS_21p', deck: "2x Corridor Creeper, 2x Devilsaur Egg, 2x Frothing Berserker, 2x Master Swordsmith, 2x Anubisath Sentinel, 2x Burly Rockjaw Trogg, 2x Cobalt Scalebane, 2x Haunted Creeper, 2x Stonesplinter Trogg, 2x Violet Wurm, 2x Zealous Initiate, 2x Gurubashi Berserker, 2x Gluttonous Trogg, 2x Battle Rage, 2x Death's Bite" },
  { hero: 'LOOTA_BOSS_22h', name: '泰德', cls: 'SHAMAN', levels: [6], hp: [20], power: 'LOOTA_BOSS_22p', deck: "Cairne Bloodhoof, King Krush, Millhouse Manastorm, Ragnaros the Firelord, Swamp King Dred, Tyrantus, Earth Elemental, Emerald Hive Queen, Flamewreathed Faceless, Starving Crab" },
  { hero: 'LOOTA_BOSS_23h', name: '布索斯納爾', cls: 'HUNTER', levels: [6, 7], hp: [50, 60], power: 'LOOTA_BOSS_23p', deck: "Gahz'rilla, Kathrena Winterwisp, King Krush, Swamp King Dred, 2x Bittertide Hydra, 2x Charged Devilsaur, 2x Giant Sand Worm, Corpse Widow, 2x King of Beasts, 2x Savannah Highmane, Giant Mastodon, 2x King's Elekk, 2x Starving Buzzard, 2x Tundra Rhino, 2x Call of the Wild, 2x Deadly Shot, 2x Kill Command, 2x Gladiator's Longbow" },
  { hero: 'LOOTA_BOSS_24h', name: '黏媽媽', cls: 'HUNTER', levels: [6, 7], hp: [50, 50], power: 'LOOTA_BOSS_24p', deck: "2x Acidic Swamp Ooze, 2x Growing Ooze, 2x Echoing Ooze, 2x Meanstreet Marshal, 2x Rat Pack, 2x Wind-up Burglebot, 2x Doppelgangster, 2x Saronite Chain Gang, 2x Green Jelly, 5x Reverberating Ooze, 2x Shroomsayer, Hogger, Doom of Elwynn, Knuckles, Sergeant Sally, 2x Solemn Vigil" },
  { hero: 'LOOTA_BOSS_38h', name: '巫毒大師維克斯', cls: 'ROGUE', levels: [6, 7], hp: [50, 60], power: 'LOOTA_BOSS_38p', deck: "2x Unearthed Raptor, 2x Abomination, 2x Bomb Squad, 2x Carnivorous Cube, 2x Rattling Rascal, 2x Shadowcaster, 2x Tomb Lurker, 2x Corpse Raiser, 2x Shallow Gravedigger, 2x Ticking Abomination, 2x Explosive Sheep, Aya Blackpaw, Sneed's Old Shredder, Sylvanas Windrunner, Xaril, Poisoned Mind" },
  { hero: 'LOOTA_BOSS_47h', name: '熔岩洞窟', cls: 'MAGE', levels: [6, 7], hp: [50, 60], power: 'LOOTA_BOSS_47p', deck: "2x Kalimos, Primal Lord, 2x Ragnaros the Firelord, 2x Fire Plume Phoenix, 2x Fireguard Destroyer, 2x Fire Elemental, 2x Forbidden Flame, 2x Pyroblast, 2x Explosive Runes, 2x Lava Burst, 2x Lava Shock, 2x Volcanic Potion, 2x Volcano, 2x Firelands Portal, 2x Flame Geyser, 2x Fireball, 2x Flamestrike" },
  { hero: 'LOOTA_BOSS_43h', name: '吉魯', cls: 'DRUID', levels: [7], hp: [40], power: 'LOOTA_BOSS_43p', deck: "Nat, the Darkfisher, 2x Dirty Rat, 2x Fel Reaver, 2x Arcane Golem, 2x Coldlight Oracle, 2x Grove Tender, 2x Acolyte of Pain, 2x Lunar Visions, 2x Ultimate Infestation, 2x Recycle, 2x Spreading Plague, 2x Living Roots, Swipe, 2x Wrath, 2x Moonfire, 2x Starfire" },
  { hero: 'LOOTA_BOSS_48h', name: '有機關的房間', cls: 'HUNTER', levels: [7], hp: [40], power: 'LOOTA_BOSS_48p', deck: "2x Ethereal Arcanist, 2x Secretkeeper, 2x Shroomsayer, Bear Trap, Snake Trap, Spellbender, Cat Trick, Counterspell, Explosive Runes, Mana Bind, Misdirection, Potion of Polymorph, Vaporize, Venomstrike Trap, Wandering Monster, Explosive Trap, Eye for an Eye, Freezing Trap, Mirror Entity, Noble Sacrifice, Repentance, Snipe, Dart Trap, Frozen Clone, Sacred Trial, Sudden Betrayal" },
  // ---------------------------------------------------------------- 第 8 關（最終 Boss）
  { hero: 'LOOTA_BOSS_99h', name: '托戈瓦哥國王', cls: 'ROGUE', levels: [8], hp: [70], power: 'LOOTA_BOSS_99p', deck: "2x Kobold Barbarian, 2x Kobold Illusionist, 2x Kobold Monk, 2x Evolved Kobold, 2x Kobold Apprentice, 2x Kobold Hermit, 2x Tomb Pillager, 2x Kobold Geomancer, 2x Beneath the Grounds, 2x Evasion, 2x Betrayal, 2x Eviscerate, 2x Sudden Betrayal, 2x Vanish, 2x Backstab" },
  { hero: 'LOOTA_BOSS_49h', name: '無邊黑暗', cls: 'PRIEST', levels: [8], hp: [70], power: 'LOOTA_BOSS_49p', deck: "2x Cabal Shadow Priest, 2x Shadowfiend, 2x Evasion, 2x Forbidden Shaping, 2x Psychic Scream, 2x Twisting Nether, 2x Entomb, 2x Potion of Madness, 2x Sudden Betrayal, 2x Mind Control, 2x Shadow Bolt, 2x Shadow Word: Death, 2x Shadow Word: Pain" },
  { hero: 'LOOTA_BOSS_34h', name: '『吞噬者』阿薩利', cls: 'WARLOCK', levels: [8], hp: [70], power: 'LOOTA_BOSS_34p', deck: "Mal'Ganis, 2x Dreadsteed, 2x Kabal Trafficker, 2x Pit Lord, 2x Voidlord, 2x Despicable Dreadlord, 2x Doomguard, 2x Abyssal Enforcer, 2x Dread Infernal, Fearsome Doomguard, 2x Flame Imp, 2x Voidcaller, 2x Wrathguard, 2x Bane of Doom, 2x DOOM!, 2x Demonwrath" },
];

/** 各職業的起始 10 張牌（Dungeon Run） */
export const DUNGEON_STARTERS: Record<Exclude<CardClass, 'NEUTRAL' | 'DEMONHUNTER' | 'DEATHKNIGHT'>, string> = {
  DRUID: 'Enchanted Raven, Power of the Wild, Tortollan Forager, Mounted Raptor, Mulch, Shade of Naxxramas, Keeper of the Grove, Savage Combatant, Swipe, Druid of the Claw',
  HUNTER: "Hunter's Mark, Stonetusk Boar, Dire Wolf Alpha, Explosive Trap, Animal Companion, Deadly Shot, Eaglehorn Bow, Jungle Panther, Unleash the Hounds, Oasis Snapjaw",
  MAGE: "Arcane Missiles, Mana Wyrm, Doomsayer, Frostbolt, Sorcerer's Apprentice, Earthen Ring Farseer, Ice Barrier, Chillwind Yeti, Fireball, Blizzard",
  PALADIN: 'Blessing of Might, Goldshire Footman, Noble Sacrifice, Argent Protector, Equality, Holy Light, Earthen Ring Farseer, Consecration, Stormwind Knight, Truesilver Champion',
  PRIEST: 'Holy Smite, Northshire Cleric, Potion of Madness, Faerie Dragon, Mind Blast, Shadow Word: Pain, Dark Cultist, Auchenai Soulpriest, Lightspawn, Holy Nova',
  ROGUE: 'Backstab, Deadly Poison, Pit Snake, Sinister Strike, Gilblin Stalker, Undercity Huckster, SI:7 Agent, Unearthed Raptor, Assassinate, Vanish',
  SHAMAN: 'Air Elemental, Lightning Bolt, Flametongue Totem, Murloc Tidehunter, Stormforged Axe, Lightning Storm, Unbound Elemental, Defender of Argus, Hex, Fire Elemental',
  WARLOCK: 'Corruption, Mortal Coil, Voidwalker, Knife Juggler, Sunfury Protector, Drain Life, Imp Master, Dark Iron Dwarf, Hellfire, Doomguard',
  WARRIOR: 'Warbot, Amani Berserker, Cruel Taskmaster, Heroic Strike, Bash, Fiery War Axe, Hired Gun, Raging Worgen, Dread Corsair, Brawl',
};
